export  const LOGIN_SUCCESS =  "LOGIN_SUCCESS"
export  const LOGIN_FAIL =  "LOGIN_FAIL"
export  const LOGIN_REQUEST =  "LOGIN_REQUEST"
export  const LOGIN_OUT =  "LOGOUT_SUCCESS"
export  const LOGIN_PROFIL =  "LOGIN_PROFIL"


export  const HOME_VIDEO_SUCCESS =  "HOME_VIDEO_SUCCESS"
export  const HOME_VIDEOS_FAIL =  "HOME_VIDEOS_FAIL"
export  const HOME_VIDEOS_REQUEST =  "HOME_VIDEOS_REQUEST"