name : Firebase Devloyment

on:
push:
  branches:
  - main


jobs:
 deploy:
  name: Buils & Deployment
  runs-on: ubuntu-latest
  steps:
  - name: Checkout repository
    uses: actions/checkout@v2

  - name: install node
    uses: actions/setup-node@v2
    with:
      node-version: '14'

  - name : install node packages
    run: npm i 

  - name : Build
    run: npm run build
    env:
     CI: false

  - name : Deploy to Firebase 
    uses: w9jds/firebase-action@v2
    with:
      args: deploy --only hosting
    env :
     FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

    
 
